# Generated by Django 2.2 on 2019-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('nome_reduzido', models.CharField(max_length=24)),
                ('unidade', models.CharField(choices=[('UN', 'Unidades'), ('KG', 'Quilogramas'), ('M', 'Metros'), ('SC', 'Sacos'), ('L', 'Litros'), ('ML', 'Mililitros'), ('M2', 'Metros quadrados'), ('CM', 'Centímetros')], max_length=3)),
                ('fornecedor', models.TextField()),
                ('fabricante', models.TextField()),
                ('ean', models.CharField(max_length=13)),
            ],
        ),
    ]
